// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechCamp.Data;

#nullable disable

namespace TechChamp.Migrations
{
    [DbContext(typeof(TechCampContext))]
    [Migration("20260921122448_SeedData2")]
    partial class SeedData2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TechCamp.Models.Dozent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Fachgebiet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nachname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dozenten");
                });

            modelBuilder.Entity("TechCamp.Models.Kurs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Beschreibung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDatum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Kursart")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxTeilnehmer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(20);

                    b.Property<int>("RaumId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDatum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Wiederholung")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("RaumId");

                    b.ToTable("Kurse");
                });

            modelBuilder.Entity("TechCamp.Models.KursDozent", b =>
                {
                    b.Property<int>("KursId")
                        .HasColumnType("int");

                    b.Property<int>("DozentId")
                        .HasColumnType("int");

                    b.HasKey("KursId", "DozentId");

                    b.HasIndex("DozentId");

                    b.ToTable("KursDozenten");
                });

            modelBuilder.Entity("TechCamp.Models.KursTeilnehmer", b =>
                {
                    b.Property<int>("KursId")
                        .HasColumnType("int");

                    b.Property<int>("TeilnehmerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AnmeldeDatum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KursId", "TeilnehmerId");

                    b.HasIndex("TeilnehmerId");

                    b.ToTable("KursTeilnehmer");
                });

            modelBuilder.Entity("TechCamp.Models.Raum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gebäude")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kapazität")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Räume");
                });

            modelBuilder.Entity("TechCamp.Models.Teilnehmer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nachname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teilnehmer");
                });

            modelBuilder.Entity("TechCamp.Models.Kurs", b =>
                {
                    b.HasOne("TechCamp.Models.Raum", "Raum")
                        .WithMany("Kurse")
                        .HasForeignKey("RaumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Raum");
                });

            modelBuilder.Entity("TechCamp.Models.KursDozent", b =>
                {
                    b.HasOne("TechCamp.Models.Dozent", "Dozent")
                        .WithMany("KursDozenten")
                        .HasForeignKey("DozentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechCamp.Models.Kurs", "Kurs")
                        .WithMany("KursDozenten")
                        .HasForeignKey("KursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dozent");

                    b.Navigation("Kurs");
                });

            modelBuilder.Entity("TechCamp.Models.KursTeilnehmer", b =>
                {
                    b.HasOne("TechCamp.Models.Kurs", "Kurs")
                        .WithMany("KursTeilnehmer")
                        .HasForeignKey("KursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechCamp.Models.Teilnehmer", "Teilnehmer")
                        .WithMany("KursTeilnehmer")
                        .HasForeignKey("TeilnehmerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kurs");

                    b.Navigation("Teilnehmer");
                });

            modelBuilder.Entity("TechCamp.Models.Dozent", b =>
                {
                    b.Navigation("KursDozenten");
                });

            modelBuilder.Entity("TechCamp.Models.Kurs", b =>
                {
                    b.Navigation("KursDozenten");

                    b.Navigation("KursTeilnehmer");
                });

            modelBuilder.Entity("TechCamp.Models.Raum", b =>
                {
                    b.Navigation("Kurse");
                });

            modelBuilder.Entity("TechCamp.Models.Teilnehmer", b =>
                {
                    b.Navigation("KursTeilnehmer");
                });
#pragma warning restore 612, 618
        }
    }
}
