// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WerkstattPro.Data;

#nullable disable

namespace WerkstattPro.Migrations
{
    [DbContext(typeof(WerkstattContext))]
    [Migration("20261002082728_SecondCreate")]
    partial class SecondCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WerkstattPro.Models.AuftragErsatzteil", b =>
                {
                    b.Property<int>("ReparaturAuftragId")
                        .HasColumnType("int");

                    b.Property<int>("ErsatzteilId")
                        .HasColumnType("int");

                    b.Property<decimal>("Einzlpreis")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Menge")
                        .HasColumnType("int");

                    b.HasKey("ReparaturAuftragId", "ErsatzteilId");

                    b.HasIndex("ErsatzteilId");

                    b.ToTable("AuftragErsatzteile");
                });

            modelBuilder.Entity("WerkstattPro.Models.AuftragMechaniker", b =>
                {
                    b.Property<int>("ReparaturAuftragId")
                        .HasColumnType("int");

                    b.Property<int>("MechanikerId")
                        .HasColumnType("int");

                    b.HasKey("ReparaturAuftragId", "MechanikerId");

                    b.HasIndex("MechanikerId");

                    b.ToTable("AuftragMechaniker");
                });

            modelBuilder.Entity("WerkstattPro.Models.Ersatzteil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Artikelnummer")
                        .HasColumnType("int");

                    b.Property<string>("Bezeichnung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Lagerbestand")
                        .HasColumnType("int");

                    b.Property<decimal>("Preis")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Ersatzteile");
                });

            modelBuilder.Entity("WerkstattPro.Models.Fahrzeug", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Baujahr")
                        .HasColumnType("datetime2");

                    b.Property<string>("Kennzeichen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KundeId")
                        .HasColumnType("int");

                    b.Property<string>("Marke")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KundeId");

                    b.ToTable("Fahrzeuge");
                });

            modelBuilder.Entity("WerkstattPro.Models.Kunde", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nachname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Telefonnummer")
                        .HasColumnType("int");

                    b.Property<string>("Vorname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kunden");
                });

            modelBuilder.Entity("WerkstattPro.Models.Mechaniker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Fachgebiet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nachname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vorname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Mechaniker");
                });

            modelBuilder.Entity("WerkstattPro.Models.ReparaturAuftrag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("AuftragsDatum")
                        .HasColumnType("date");

                    b.Property<string>("Beschreibung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FahrzeugId")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("FahrzeugId");

                    b.ToTable("ReparaturAuftraege");
                });

            modelBuilder.Entity("WerkstattPro.Models.AuftragErsatzteil", b =>
                {
                    b.HasOne("WerkstattPro.Models.Ersatzteil", "Ersatzteil")
                        .WithMany("AuftragErsatzteils")
                        .HasForeignKey("ErsatzteilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WerkstattPro.Models.ReparaturAuftrag", "ReparaturAuftrag")
                        .WithMany("AuftragErsatzteil")
                        .HasForeignKey("ReparaturAuftragId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ersatzteil");

                    b.Navigation("ReparaturAuftrag");
                });

            modelBuilder.Entity("WerkstattPro.Models.AuftragMechaniker", b =>
                {
                    b.HasOne("WerkstattPro.Models.Mechaniker", "Mechaniker")
                        .WithMany("AuftragMechanikers")
                        .HasForeignKey("MechanikerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WerkstattPro.Models.ReparaturAuftrag", "ReparaturAuftrag")
                        .WithMany("AuftragMechaniker")
                        .HasForeignKey("ReparaturAuftragId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mechaniker");

                    b.Navigation("ReparaturAuftrag");
                });

            modelBuilder.Entity("WerkstattPro.Models.Fahrzeug", b =>
                {
                    b.HasOne("WerkstattPro.Models.Kunde", "Kunde")
                        .WithMany("Fahrzeuge")
                        .HasForeignKey("KundeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kunde");
                });

            modelBuilder.Entity("WerkstattPro.Models.ReparaturAuftrag", b =>
                {
                    b.HasOne("WerkstattPro.Models.Fahrzeug", "Fahrzeug")
                        .WithMany("ReparaturAufträge")
                        .HasForeignKey("FahrzeugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fahrzeug");
                });

            modelBuilder.Entity("WerkstattPro.Models.Ersatzteil", b =>
                {
                    b.Navigation("AuftragErsatzteils");
                });

            modelBuilder.Entity("WerkstattPro.Models.Fahrzeug", b =>
                {
                    b.Navigation("ReparaturAufträge");
                });

            modelBuilder.Entity("WerkstattPro.Models.Kunde", b =>
                {
                    b.Navigation("Fahrzeuge");
                });

            modelBuilder.Entity("WerkstattPro.Models.Mechaniker", b =>
                {
                    b.Navigation("AuftragMechanikers");
                });

            modelBuilder.Entity("WerkstattPro.Models.ReparaturAuftrag", b =>
                {
                    b.Navigation("AuftragErsatzteil");

                    b.Navigation("AuftragMechaniker");
                });
#pragma warning restore 612, 618
        }
    }
}
